"""initial schema

Revision ID: 021eeffc43f5
Revises: 
Create Date: 2026-08-19 18:13:18.360282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021eeffc43f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('borrowers',
    sa.Column('borrower_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('revolving_utilization_of_unsecured_lines', sa.Float(), nullable=False),
    sa.Column('number_of_time_30_59_days_past_due_not_worse', sa.Integer(), nullable=False),
    sa.Column('debt_ratio', sa.Float(), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('number_of_open_credit_lines_and_loans', sa.Integer(), nullable=False),
    sa.Column('number_of_times_90_days_late', sa.Integer(), nullable=False),
    sa.Column('number_real_estate_loans_or_lines', sa.Integer(), nullable=False),
    sa.Column('number_of_time_60_89_days_past_due_not_worse', sa.Integer(), nullable=False),
    sa.Column('number_of_dependents', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('borrower_id')
    )
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_table('risk_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=20), nullable=False),
    sa.Column('risk_type', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=20), nullable=True),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('shocks', sa.JSON(), nullable=False),
    sa.Column('market_loss', sa.Float(), nullable=True),
    sa.Column('credit_loss', sa.Float(), nullable=True),
    sa.Column('combined_loss', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('loan_id', sa.String(length=20), nullable=False),
    sa.Column('borrower_id', sa.String(length=20), nullable=False),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('recovery_rate', sa.Float(), nullable=False),
    sa.Column('origination_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.borrower_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.loan_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('portfolio_holdings')
    op.drop_table('market_prices')
    op.drop_table('loans')
    op.drop_table('stress_results')
    op.drop_table('risk_results')
    op.drop_table('portfolios')
    op.drop_table('borrowers')
    op.drop_table('assets')
    # ### end Alembic commands ###
